language: php

php: [5.4, 5.5, 5.6, 7.0, hhvm]

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
        - env: SYMFONY_VERSION='2.7.*@dev'
        - php: 7.0
    include:
        - php: 5.4
          env: SYMFONY_VERSION='2.4.*'
        - php: 5.4
          env: SYMFONY_VERSION='2.5.*'
        - php: 5.4
          env: SYMFONY_VERSION='2.6.*'
        - php: 5.4
          env: SYMFONY_VERSION='2.7.*@dev'

before_script:
    - composer selfupdate
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony=$SYMFONY_VERSION; else composer install; fi;
    - phantomjs --version
    - phantomjs --webdriver=4444 &
    - php -S localhost:8080 -t features/Context/fixtures &
    - 'curl -H "Accept: text/plain" https://security.sensiolabs.org/check_lock -F lock=@composer.lock -s | grep "No known"'

script:
    - ./bin/phpspec run -fpretty
    - ./bin/behat --verbose
