language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION='2.0.*'
  - SYMFONY_VERSION='2.1.*'
  - SYMFONY_VERSION='2.2.*@dev'

before_script:
  - composer require --no-update symfony/symfony=$SYMFONY_VERSION
  - composer install --prefer-source --dev

script: ./bin/phpspec run -fpretty
