# KnpRad layer configuration
# Docs: http://rad.knplabs.org

all:
    # Don't touch this parameters unless you're really
    # sure of what you're doing. Switching those options
    # off will not give you noticable performance boost :-)
    application_routing:     true
    application_shortaction: true
    application_views:       true

    assetic_pipeline:
        enabled:  true
        paths:
            # Put additional paths here in order
            # in which you want pipelined assets should
            # be searched
            - %kernel.project_dir%/Resources/public
            - %kernel.root_dir%/vendor/assets

        # By default, pipeline will search for assets inside
        # every bundle too (paths section have higher priority though)
        # but if you want to limit search to some specific bundles,
        # list their names in this section:
        # bundles:
        #     - FrameworkBundle
        #     - ...
